let updatedData = [
  {
    id: 1,
    name: "Afghanistan",
    short_name: "AFG",
    status: "Country",
    dial_code: "+93",
    max_nsn_length: 9,
    flags_icon: "flags/af.svg",
    national_language: "Dari",
  },
  {
    id: 2,
    name: "Åland Islands",
    short_name: "AX",
    status: "Territory (Finland)",
    dial_code: "+358",
    max_nsn_length: 11,
    flags_icon: "flags/ax.svg",
    national_language: "Swedish",
  },
  {
    id: 3,
    name: "Albania",
    short_name: "ALB",
    status: "Country",
    dial_code: "+355",
    max_nsn_length: 9,
    flags_icon: "flags/al.svg",
    national_language: "Albanian",
  },
  {
    id: 4,
    name: "Algeria",
    short_name: "DZA",
    status: "Country",
    dial_code: "+213",
    max_nsn_length: 9,
    flags_icon: "flags/dz.svg",
    national_language: "Arabic",
  },
  {
    id: 5,
    name: "American Samoa",
    short_name: "AS",
    status: "Territory (USA)",
    dial_code: "+1-684",
    max_nsn_length: 10,
    flags_icon: "flags/as.svg",
    national_language: "English",
  },
  {
    id: 6,
    name: "Andorra",
    short_name: "AND",
    status: "Country",
    dial_code: "+376",
    max_nsn_length: 9,
    flags_icon: "flags/ad.svg",
    national_language: "Catalan",
  },
  {
    id: 7,
    name: "Angola",
    short_name: "AGO",
    status: "Country",
    dial_code: "+244",
    max_nsn_length: 9,
    flags_icon: "flags/ao.svg",
    national_language: "Portuguese",
  },
  {
    id: 8,
    name: "Anguilla",
    short_name: "AI",
    status: "Territory (UK)",
    dial_code: "+1-264",
    max_nsn_length: 10,
    flags_icon: "flags/ai.svg",
    national_language: "English",
  },
  {
    id: 9,
    name: "Antarctica",
    short_name: "ATG",
    status: "Country",
    dial_code: "+1-268",
    max_nsn_length: 10,
    flags_icon: "flags/aq.svg",
    national_language: "N/A",
  },
  {
    id: 10,
    name: "Antigua and Barbuda",
    short_name: "ATG",
    status: "Country",
    dial_code: "+1-268",
    max_nsn_length: 10,
    flags_icon: "flags/ag.svg",
    national_language: "English",
  },
  {
    id: 11,
    name: "Argentina",
    short_name: "ARG",
    status: "Country",
    dial_code: "+54",
    max_nsn_length: 11,
    flags_icon: "flags/ar.svg",
    national_language: "Spanish",
  },
  {
    id: 12,
    name: "Armenia",
    short_name: "ARM",
    status: "Country",
    dial_code: "+374",
    max_nsn_length: 8,
    flags_icon: "flags/am.svg",
    national_language: "Armenian",
  },
  {
    id: 13,
    name: "Aruba",
    short_name: "AW",
    status: "Territory (Netherlands)",
    dial_code: "+297",
    max_nsn_length: 7,
    flags_icon: "flags/aw.svg",
    national_language: "Dutch",
  },
  {
    id: 14,
    name: "Australia",
    short_name: "AUS",
    status: "Country",
    dial_code: "+61",
    max_nsn_length: 9,
    flags_icon: "flags/au.svg",
    national_language: "English",
  },
  {
    id: 15,
    name: "Austria",
    short_name: "AUT",
    status: "Country",
    dial_code: "+43",
    max_nsn_length: 13,
    flags_icon: "flags/at.svg",
    national_language: "German",
  },
  {
    id: 16,
    name: "Azerbaijan",
    short_name: "AZE",
    status: "Country",
    dial_code: "+994",
    max_nsn_length: 9,
    flags_icon: "flags/az.svg",
    national_language: "Azerbaijani",
  },
  {
    id: 17,
    name: "Bahamas",
    short_name: "BHS",
    status: "Country",
    dial_code: "+1-242",
    max_nsn_length: 10,
    flags_icon: "flags/bs.svg",
    national_language: "English",
  },
  {
    id: 18,
    name: "Bahrain",
    short_name: "BHR",
    status: "Country",
    dial_code: "+973",
    max_nsn_length: 8,
    flags_icon: "flags/bh.svg",
    national_language: "Arabic",
  },
  {
    id: 19,
    name: "Bangladesh",
    short_name: "BGD",
    status: "Country",
    dial_code: "+880",
    max_nsn_length: 10,
    flags_icon: "flags/bd.svg",
    national_language: "Bengali",
  },
  {
    id: 20,
    name: "Barbados",
    short_name: "BRB",
    status: "Country",
    dial_code: "+1-246",
    max_nsn_length: 10,
    flags_icon: "flags/bb.svg",
    national_language: "English",
  },
  {
    id: 21,
    name: "Belarus",
    short_name: "BLR",
    status: "Country",
    dial_code: "+375",
    max_nsn_length: 10,
    flags_icon: "flags/by.svg",
    national_language: "Belarusian",
  },
  {
    id: 22,
    name: "Belgium",
    short_name: "BEL",
    status: "Country",
    dial_code: "+32",
    max_nsn_length: 9,
    flags_icon: "flags/be.svg",
    national_language: "Dutch",
  },
  {
    id: 23,
    name: "Belize",
    short_name: "BLZ",
    status: "Country",
    dial_code: "+501",
    max_nsn_length: 7,
    flags_icon: "flags/bz.svg",
    national_language: "English",
  },
  {
    id: 24,
    name: "Benin",
    short_name: "BEN",
    status: "Country",
    dial_code: "+229",
    max_nsn_length: 8,
    flags_icon: "flags/bj.svg",
    national_language: "French",
  },
  {
    id: 25,
    name: "Bermuda",
    short_name: "BM",
    status: "Territory (UK)",
    dial_code: "+1-441",
    max_nsn_length: 10,
    flags_icon: "flags/bm.svg",
    national_language: "English",
  },
  {
    id: 26,
    name: "Bhutan",
    short_name: "BTN",
    status: "Country",
    dial_code: "+975",
    max_nsn_length: 8,
    flags_icon: "flags/bt.svg",
    national_language: "Dzongkha",
  },
  {
    id: 27,
    name: "Bolivia",
    short_name: "BOL",
    status: "Country",
    dial_code: "+591",
    max_nsn_length: 8,
    flags_icon: "flags/bo.svg",
    national_language: "Spanish",
  },
  {
    id: 28,
    name: "Bonaire, Sint Eustatius and Saba",
    short_name: "BES",
    status: "Territory (Netherlands)",
    dial_code: "+599",
    max_nsn_length: 7,
    flags_icon: "flags/bq.svg",
    national_language: "Dutch",
  },
  {
    id: 29,
    name: "Bosnia and Herzegovina",
    short_name: "BIH",
    status: "Country",
    dial_code: "+387",
    max_nsn_length: 8,
    flags_icon: "flags/ba.svg",
    national_language: "Bosnian",
  },
  {
    id: 30,
    name: "Botswana",
    short_name: "BWA",
    status: "Country",
    dial_code: "+267",
    max_nsn_length: 8,
    flags_icon: "flags/bw.svg",
    national_language: "English",
  },
  {
    id: 31,
    name: "Bouvet Island",
    short_name: "BV",
    status: "Country",
    dial_code: "+47",
    max_nsn_length: 8,
    flags_icon: "flags/bv.svg",
    national_language: "Norwegian",
  },
  {
    id: 32,
    name: "Brazil",
    short_name: "BRA",
    status: "Country",
    dial_code: "+55",
    max_nsn_length: 11,
    flags_icon: "flags/br.svg",
    national_language: "Portuguese",
  },
  {
    id: 33,
    name: "British Indian Ocean Territory",
    short_name: "IO",
    status: "Territory (UK)",
    dial_code: "+246",
    max_nsn_length: 7,
    flags_icon: "flags/io.svg",
    national_language: "English",
  },
  {
    id: 34,
    name: "Brunei",
    short_name: "BRN",
    status: "Country",
    dial_code: "+673",
    max_nsn_length: 7,
    flags_icon: "flags/bn.svg",
    national_language: "Malay",
  },
  {
    id: 35,
    name: "Bulgaria",
    short_name: "BGR",
    status: "Country",
    dial_code: "+359",
    max_nsn_length: 9,
    flags_icon: "flags/bg.svg",
    national_language: "Bulgarian",
  },
  {
    id: 36,
    name: "Burkina Faso",
    short_name: "BFA",
    status: "Country",
    dial_code: "+226",
    max_nsn_length: 8,
    flags_icon: "flags/bf.svg",
    national_language: "French",
  },
  {
    id: 37,
    name: "Burundi",
    short_name: "BDI",
    status: "Country",
    dial_code: "+257",
    max_nsn_length: 8,
    flags_icon: "flags/bi.svg",
    national_language: "Kirundi",
  },
  {
    id: 38,
    name: "Cabo Verde",
    short_name: "CPV",
    status: "Country",
    dial_code: "+238",
    max_nsn_length: 7,
    flags_icon: "flags/cv.svg",
    national_language: "Portuguese",
  },
  {
    id: 39,
    name: "Cambodia",
    short_name: "KHM",
    status: "Country",
    dial_code: "+855",
    max_nsn_length: 9,
    flags_icon: "flags/kh.svg",
    national_language: "Khmer",
  },
  {
    id: 40,
    name: "Cameroon",
    short_name: "CMR",
    status: "Country",
    dial_code: "+237",
    max_nsn_length: 9,
    flags_icon: "flags/cm.svg",
    national_language: "French",
  },
  {
    id: 41,
    name: "Canada",
    short_name: "CAN",
    status: "Country",
    dial_code: "+1",
    max_nsn_length: 10,
    flags_icon: "flags/ca.svg",
    national_language: "English",
  },
  {
    id: 42,
    name: "Cayman Islands",
    short_name: "KY",
    status: "Territory (UK)",
    dial_code: "+1-345",
    max_nsn_length: 10,
    flags_icon: "flags/ky.svg",
    national_language: "English",
  },
  {
    id: 43,
    name: "Central African Republic",
    short_name: "CAF",
    status: "Country",
    dial_code: "+236",
    max_nsn_length: 8,
    flags_icon: "flags/cf.svg",
    national_language: "French",
  },
  {
    id: 44,
    name: "Chad",
    short_name: "TCD",
    status: "Country",
    dial_code: "+235",
    max_nsn_length: 8,
    flags_icon: "flags/td.svg",
    national_language: "French",
  },
  {
    id: 45,
    name: "Chile",
    short_name: "CHL",
    status: "Country",
    dial_code: "+56",
    max_nsn_length: 9,
    flags_icon: "flags/cl.svg",
    national_language: "Spanish",
  },
  {
    id: 46,
    name: "China",
    short_name: "CHN",
    status: "Country",
    dial_code: "+86",
    max_nsn_length: 11,
    flags_icon: "flags/cn.svg",
    national_language: "Mandarin Chinese",
  },
  {
    id: 47,
    name: "Christmas Island",
    short_name: "CX",
    status: "Territory (Australia)",
    dial_code: "+61",
    max_nsn_length: 9,
    flags_icon: "flags/cx.svg",
    national_language: "English",
  },
  {
    id: 48,
    name: "Cocos (Keeling) Islands",
    short_name: "CC",
    status: "Territory (Australia)",
    dial_code: "+61",
    max_nsn_length: 9,
    flags_icon: "flags/cc.svg",
    national_language: "English",
  },
  {
    id: 49,
    name: "Colombia",
    short_name: "COL",
    status: "Country",
    dial_code: "+57",
    max_nsn_length: 10,
    flags_icon: "flags/co.svg",
    national_language: "Spanish",
  },
  {
    id: 50,
    name: "Comoros",
    short_name: "COM",
    status: "Country",
    dial_code: "+269",
    max_nsn_length: 7,
    flags_icon: "flags/km.svg",
    national_language: "Comorian",
  },
  {
    id: 49,
    name: "Congo (Brazzaville)",
    short_name: "COG",
    status: "Country",
    dial_code: "+242",
    max_nsn_length: 9,
    flags_icon: "flags/cg.svg",
    national_language: "French",
  },
  {
    id: 50,
    name: "Congo (Kinshasa)",
    short_name: "DRC",
    status: "Country",
    dial_code: "+243",
    max_nsn_length: 9,
    flags_icon: "flags/cd.svg",
    national_language: "French",
  },
  {
    id: 51,
    name: "Cook Islands",
    short_name: "CK",
    status: "Territory (New Zealand)",
    dial_code: "+682",
    max_nsn_length: 5,
    flags_icon: "flags/ck.svg",
    national_language: "Māori (Cook Islands)",
  },
  {
    id: 52,
    name: "Costa Rica",
    short_name: "CRI",
    status: "Country",
    dial_code: "+506",
    max_nsn_length: 8,
    flags_icon: "flags/cr.svg",
    national_language: "Spanish",
  },
  {
    id: 53,
    name: "Côte d'Ivoire (Ivory Coast)",
    short_name: "CIV",
    status: "Country",
    dial_code: "+225",
    max_nsn_length: 10,
    flags_icon: "flags/ci.svg",
    national_language: "French",
  },
  {
    id: 54,
    name: "Croatia",
    short_name: "HRV",
    status: "Country",
    dial_code: "+385",
    max_nsn_length: 9,
    flags_icon: "flags/hr.svg",
    national_language: "Croatian",
  },
  {
    id: 55,
    name: "Cuba",
    short_name: "CUB",
    status: "Country",
    dial_code: "+53",
    max_nsn_length: 8,
    flags_icon: "flags/cu.svg",
    national_language: "Spanish",
  },
  {
    id: 56,
    name: "Curaçao",
    short_name: "CW",
    status: "Territory (Netherlands)",
    dial_code: "+599",
    max_nsn_length: 7,
    flags_icon: "flags/cw.svg",
    national_language: "Papiamento",
  },
  {
    id: 57,
    name: "Cyprus",
    short_name: "CYP",
    status: "Country",
    dial_code: "+357",
    max_nsn_length: 8,
    flags_icon: "flags/cy.svg",
    national_language: "Greek",
  },
  {
    id: 58,
    name: "Czechia (Czech Republic)",
    short_name: "CZE",
    status: "Country",
    dial_code: "+420",
    max_nsn_length: 9,
    flags_icon: "flags/cz.svg",
    national_language: "Czech",
  },
  {
    id: 59,
    name: "Denmark",
    short_name: "DNK",
    status: "Country",
    dial_code: "+45",
    max_nsn_length: 8,
    flags_icon: "flags/dk.svg",
    national_language: "Danish",
  },
  {
    id: 60,
    name: "Djibouti",
    short_name: "DJI",
    status: "Country",
    dial_code: "+253",
    max_nsn_length: 8,
    flags_icon: "flags/dj.svg",
    national_language: "French",
  },
  {
    id: 61,
    name: "Dominica",
    short_name: "DMA",
    status: "Country",
    dial_code: "+1-767",
    max_nsn_length: 10,
    flags_icon: "flags/dm.svg",
    national_language: "English",
  },
  {
    id: 62,
    name: "Dominican Republic",
    short_name: "DOM",
    status: "Country",
    dial_code: "+1-809",
    max_nsn_length: 10,
    flags_icon: "flags/do.svg",
    national_language: "Spanish",
  },
  {
    id: 63,
    name: "Ecuador",
    short_name: "ECU",
    status: "Country",
    dial_code: "+593",
    max_nsn_length: 9,
    flags_icon: "flags/ec.svg",
    national_language: "Spanish",
  },
  {
    id: 64,
    name: "Egypt",
    short_name: "EGY",
    status: "Country",
    dial_code: "+20",
    max_nsn_length: 10,
    flags_icon: "flags/eg.svg",
    national_language: "Arabic",
  },
  {
    id: 65,
    name: "El Salvador",
    short_name: "SLV",
    status: "Country",
    dial_code: "+503",
    max_nsn_length: 8,
    flags_icon: "flags/sv.svg",
    national_language: "Spanish",
  },
  {
    id: 66,
    name: "Equatorial Guinea",
    short_name: "GNQ",
    status: "Country",
    dial_code: "+240",
    max_nsn_length: 9,
    flags_icon: "flags/gq.svg",
    national_language: "Spanish",
  },
  {
    id: 67,
    name: "Eritrea",
    short_name: "ERI",
    status: "Country",
    dial_code: "+291",
    max_nsn_length: 7,
    flags_icon: "flags/er.svg",
    national_language: "Tigrinya",
  },
  {
    id: 68,
    name: "Estonia",
    short_name: "EST",
    status: "Country",
    dial_code: "+372",
    max_nsn_length: 8,
    flags_icon: "flags/ee.svg",
    national_language: "Estonian",
  },
  {
    id: 69,
    name: "Eswatini",
    short_name: "SWZ",
    status: "Country",
    dial_code: "+268",
    max_nsn_length: 8,
    flags_icon: "flags/sz.svg",
    national_language: "Swazi",
  },
  {
    id: 70,
    name: "Ethiopia",
    short_name: "ETH",
    status: "Country",
    dial_code: "+251",
    max_nsn_length: 9,
    flags_icon: "flags/et.svg",
    national_language: "Amharic",
  },
  {
    id: 71,
    name: "Falkland Islands",
    short_name: "FK",
    status: "Territory (UK)",
    dial_code: "+500",
    max_nsn_length: 5,
    flags_icon: "flags/fk.svg",
    national_language: "English",
  },
  {
    id: 72,
    name: "Faroe Islands",
    short_name: "FO",
    status: "Territory (Denmark)",
    dial_code: "+298",
    max_nsn_length: 6,
    flags_icon: "flags/fo.svg",
    national_language: "Faroese",
  },
  {
    id: 73,
    name: "Fiji",
    short_name: "FJI",
    status: "Country",
    dial_code: "+679",
    max_nsn_length: 8,
    flags_icon: "flags/fj.svg",
    national_language: "Fijian",
  },
  {
    id: 74,
    name: "Finland",
    short_name: "FIN",
    status: "Country",
    dial_code: "+358",
    max_nsn_length: 12,
    flags_icon: "flags/fi.svg",
    national_language: "Finnish",
  },
  {
    id: 75,
    name: "France",
    short_name: "FRA",
    status: "Country",
    dial_code: "+33",
    max_nsn_length: 9,
    flags_icon: "flags/fr.svg",
    national_language: "French",
  },
  {
    id: 76,
    name: "French Guiana",
    short_name: "GF",
    status: "Territory (France)",
    dial_code: "+594",
    max_nsn_length: 9,
    flags_icon: "flags/gf.svg",
    national_language: "French",
  },
  {
    id: 77,
    name: "French Polynesia",
    short_name: "PF",
    status: "Territory (France)",
    dial_code: "+689",
    max_nsn_length: 8,
    flags_icon: "flags/pf.svg",
    national_language: "French",
  },
  {
    id: 78,
    name: "Gabon",
    short_name: "GAB",
    status: "Country",
    dial_code: "+241",
    max_nsn_length: 8,
    flags_icon: "flags/ga.svg",
    national_language: "French",
  },
  {
    id: 79,
    name: "Gambia, The",
    short_name: "GMB",
    status: "Country",
    dial_code: "+220",
    max_nsn_length: 7,
    flags_icon: "flags/gm.svg",
    national_language: "English",
  },
  {
    id: 80,
    name: "Georgia",
    short_name: "GEO",
    status: "Country",
    dial_code: "+995",
    max_nsn_length: 9,
    flags_icon: "flags/ge.svg",
    national_language: "Georgian",
  },
  {
    id: 81,
    name: "Germany",
    short_name: "DEU",
    status: "Country",
    dial_code: "+49",
    max_nsn_length: 13,
    flags_icon: "flags/de.svg",
    national_language: "German",
  },
  {
    id: 82,
    name: "Ghana",
    short_name: "GHA",
    status: "Country",
    dial_code: "+233",
    max_nsn_length: 9,
    flags_icon: "flags/gh.svg",
    national_language: "English",
  },
  {
    id: 83,
    name: "Gibraltar",
    short_name: "GI",
    status: "Territory (UK)",
    dial_code: "+350",
    max_nsn_length: 8,
    flags_icon: "flags/gi.svg",
    national_language: "English",
  },
  {
    id: 84,
    name: "Greece",
    short_name: "GRC",
    status: "Country",
    dial_code: "+30",
    max_nsn_length: 10,
    flags_icon: "flags/gr.svg",
    national_language: "Greek",
  },
  {
    id: 85,
    name: "Greenland",
    short_name: "GL",
    status: "Territory (Denmark)",
    dial_code: "+299",
    max_nsn_length: 6,
    flags_icon: "flags/gl.svg",
    national_language: "Greenlandic",
  },
  {
    id: 86,
    name: "Grenada",
    short_name: "GRD",
    status: "Country",
    dial_code: "+1-473",
    max_nsn_length: 10,
    flags_icon: "flags/gd.svg",
    national_language: "English",
  },
  {
    id: 87,
    name: "Guadeloupe",
    short_name: "GP",
    status: "Territory (France)",
    dial_code: "+590",
    max_nsn_length: 9,
    flags_icon: "flags/gp.svg",
    national_language: "French",
  },
  {
    id: 88,
    name: "Guam",
    short_name: "GU",
    status: "Territory (USA)",
    dial_code: "+1-671",
    max_nsn_length: 10,
    flags_icon: "flags/gu.svg",
    national_language: "English",
  },
  {
    id: 89,
    name: "Guatemala",
    short_name: "GTM",
    status: "Country",
    dial_code: "+502",
    max_nsn_length: 8,
    flags_icon: "flags/gt.svg",
    national_language: "Spanish",
  },
  {
    id: 90,
    name: "Guernsey",
    short_name: "GG",
    status: "Territory (UK Crown Dependency)",
    dial_code: "+44-1481",
    max_nsn_length: 10,
    flags_icon: "flags/gg.svg",
    national_language: "English",
  },
  {
    id: 91,
    name: "Guinea",
    short_name: "GIN",
    status: "Country",
    dial_code: "+224",
    max_nsn_length: 9,
    flags_icon: "flags/gn.svg",
    national_language: "French",
  },
  {
    id: 92,
    name: "Guinea-Bissau",
    short_name: "GNB",
    status: "Country",
    dial_code: "+245",
    max_nsn_length: 9,
    flags_icon: "flags/gw.svg",
    national_language: "Portuguese",
  },
  {
    id: 93,
    name: "Guyana",
    short_name: "GUY",
    status: "Country",
    dial_code: "+592",
    max_nsn_length: 7,
    flags_icon: "flags/gy.svg",
    national_language: "English",
  },
  {
    id: 94,
    name: "Haiti",
    short_name: "HTI",
    status: "Country",
    dial_code: "+509",
    max_nsn_length: 8,
    flags_icon: "flags/ht.svg",
    national_language: "Haitian Creole",
  },
  {
    id: 95,
    name: "Holy See (Vatican City)",
    short_name: "VAT",
    status: "Observer State",
    dial_code: "+379",
    max_nsn_length: 10,
    flags_icon: "flags/va.svg",
    national_language: "Latin",
  },
  {
    id: 96,
    name: "Honduras",
    short_name: "HND",
    status: "Country",
    dial_code: "+504",
    max_nsn_length: 8,
    flags_icon: "flags/hn.svg",
    national_language: "Spanish",
  },
  {
    id: 97,
    name: "Hong Kong",
    short_name: "HK",
    status: "Territory (China SAR)",
    dial_code: "+852",
    max_nsn_length: 8,
    flags_icon: "flags/hk.svg",
    national_language: "Chinese (Cantonese)",
  },
  {
    id: 98,
    name: "Hungary",
    short_name: "HUN",
    status: "Country",
    dial_code: "+36",
    max_nsn_length: 9,
    flags_icon: "flags/hu.svg",
    national_language: "Hungarian",
  },
  {
    id: 99,
    name: "Iceland",
    short_name: "ISL",
    status: "Country",
    dial_code: "+354",
    max_nsn_length: 9,
    flags_icon: "flags/is.svg",
    national_language: "Icelandic",
  },
  {
    id: 100,
    name: "India",
    short_name: "IND",
    status: "Country",
    dial_code: "+91",
    max_nsn_length: 10,
    flags_icon: "flags/in.svg",
    national_language: "Hindi",
  },
  {
    id: 101,
    name: "Indonesia",
    short_name: "IDN",
    status: "Country",
    dial_code: "+62",
    max_nsn_length: 11,
    flags_icon: "flags/id.svg",
    national_language: "Indonesian",
  },
  {
    id: 102,
    name: "Iran",
    short_name: "IRN",
    status: "Country",
    dial_code: "+98",
    max_nsn_length: 10,
    flags_icon: "flags/ir.svg",
    national_language: "Persian (Farsi)",
  },
  {
    id: 103,
    name: "Iraq",
    short_name: "IRQ",
    status: "Country",
    dial_code: "+964",
    max_nsn_length: 10,
    flags_icon: "flags/iq.svg",
    national_language: "Arabic",
  },
  {
    id: 104,
    name: "Ireland",
    short_name: "IRL",
    status: "Country",
    dial_code: "+353",
    max_nsn_length: 9,
    flags_icon: "flags/ie.svg",
    national_language: "Irish (Gaeilge)",
  },
  {
    id: 105,
    name: "Isle of Man",
    short_name: "IM",
    status: "Territory (UK Crown Dependency)",
    dial_code: "+44-1624",
    max_nsn_length: 10,
    flags_icon: "flags/im.svg",
    national_language: "English",
  },
  {
    id: 106,
    name: "Israel",
    short_name: "ISR",
    status: "Country",
    dial_code: "+972",
    max_nsn_length: 9,
    flags_icon: "flags/il.svg",
    national_language: "Hebrew",
  },
  {
    id: 107,
    name: "Italy",
    short_name: "ITA",
    status: "Country",
    dial_code: "+39",
    max_nsn_length: 11,
    flags_icon: "flags/it.svg",
    national_language: "Italian",
  },
  {
    id: 108,
    name: "Jamaica",
    short_name: "JAM",
    status: "Country",
    dial_code: "+1-876",
    max_nsn_length: 10,
    flags_icon: "flags/jm.svg",
    national_language: "English",
  },
  {
    id: 109,
    name: "Japan",
    short_name: "JPN",
    status: "Country",
    dial_code: "+81",
    max_nsn_length: 10,
    flags_icon: "flags/jp.svg",
    national_language: "Japanese",
  },
  {
    id: 110,
    name: "Jersey",
    short_name: "JE",
    status: "Territory (UK Crown Dependency)",
    dial_code: "+44-1534",
    max_nsn_length: 10,
    flags_icon: "flags/je.svg",
    national_language: "English",
  },
  {
    id: 111,
    name: "Jordan",
    short_name: "JOR",
    status: "Country",
    dial_code: "+962",
    max_nsn_length: 9,
    flags_icon: "flags/jo.svg",
    national_language: "Arabic",
  },
  {
    id: 112,
    name: "Kazakhstan",
    short_name: "KAZ",
    status: "Country",
    dial_code: "+7",
    max_nsn_length: 10,
    flags_icon: "flags/kz.svg",
    national_language: "Kazakh",
  },
  {
    id: 113,
    name: "Kenya",
    short_name: "KEN",
    status: "Country",
    dial_code: "+254",
    max_nsn_length: 9,
    flags_icon: "flags/ke.svg",
    national_language: "Swahili",
  },
  {
    id: 114,
    name: "Kiribati",
    short_name: "KIR",
    status: "Country",
    dial_code: "+686",
    max_nsn_length: 8,
    flags_icon: "flags/ki.svg",
    national_language: "Gilbertese (I-Kiribati)",
  },
  {
    id: 115,
    name: "Kosovo",
    short_name: "KOS",
    status: "Country (Partial Recognition)",
    dial_code: "+383",
    max_nsn_length: 8,
    flags_icon: "flags/xk.svg",
    national_language: "Albanian",
  },
  {
    id: 116,
    name: "Kuwait",
    short_name: "KWT",
    status: "Country",
    dial_code: "+965",
    max_nsn_length: 8,
    flags_icon: "flags/kw.svg",
    national_language: "Arabic",
  },
  {
    id: 117,
    name: "Kyrgyzstan",
    short_name: "KGZ",
    status: "Country",
    dial_code: "+996",
    max_nsn_length: 9,
    flags_icon: "flags/kg.svg",
    national_language: "Kyrgyz",
  },
  {
    id: 118,
    name: "Laos",
    short_name: "LAO",
    status: "Country",
    dial_code: "+856",
    max_nsn_length: 8,
    flags_icon: "flags/la.svg",
    national_language: "Lao",
  },
  {
    id: 119,
    name: "Latvia",
    short_name: "LVA",
    status: "Country",
    dial_code: "+371",
    max_nsn_length: 8,
    flags_icon: "flags/lv.svg",
    national_language: "Latvian",
  },
  {
    id: 120,
    name: "Lebanon",
    short_name: "LBN",
    status: "Country",
    dial_code: "+961",
    max_nsn_length: 8,
    flags_icon: "flags/lb.svg",
    national_language: "Arabic",
  },
  {
    id: 121,
    name: "Lesotho",
    short_name: "LSO",
    status: "Country",
    dial_code: "+266",
    max_nsn_length: 8,
    flags_icon: "flags/ls.svg",
    national_language: "Sotho",
  },
  {
    id: 122,
    name: "Liberia",
    short_name: "LBR",
    status: "Country",
    dial_code: "+231",
    max_nsn_length: 8,
    flags_icon: "flags/lr.svg",
    national_language: "English",
  },
  {
    id: 123,
    name: "Libya",
    short_name: "LBY",
    status: "Country",
    dial_code: "+218",
    max_nsn_length: 9,
    flags_icon: "flags/ly.svg",
    national_language: "Arabic",
  },
  {
    id: 124,
    name: "Liechtenstein",
    short_name: "LIE",
    status: "Country",
    dial_code: "+423",
    max_nsn_length: 9,
    flags_icon: "flags/li.svg",
    national_language: "German",
  },
  {
    id: 125,
    name: "Lithuania",
    short_name: "LTU",
    status: "Country",
    dial_code: "+370",
    max_nsn_length: 8,
    flags_icon: "flags/lt.svg",
    national_language: "Lithuanian",
  },
  {
    id: 126,
    name: "Luxembourg",
    short_name: "LUX",
    status: "Country",
    dial_code: "+352",
    max_nsn_length: 9,
    flags_icon: "flags/lu.svg",
    national_language: "Luxembourgish",
  },
  {
    id: 127,
    name: "Macao",
    short_name: "MO",
    status: "Territory (China SAR)",
    dial_code: "+853",
    max_nsn_length: 8,
    flags_icon: "flags/mo.svg",
    national_language: "Chinese (Cantonese)",
  },
  {
    id: 128,
    name: "Madagascar",
    short_name: "MDG",
    status: "Country",
    dial_code: "+261",
    max_nsn_length: 9,
    flags_icon: "flags/mg.svg",
    national_language: "Malagasy",
  },
  {
    id: 129,
    name: "Malawi",
    short_name: "MWI",
    status: "Country",
    dial_code: "+265",
    max_nsn_length: 8,
    flags_icon: "flags/mw.svg",
    national_language: "Chichewa",
  },
  {
    id: 130,
    name: "Malaysia",
    short_name: "MYS",
    status: "Country",
    dial_code: "+60",
    max_nsn_length: 10,
    flags_icon: "flags/my.svg",
    national_language: "Malay",
  },
  {
    id: 131,
    name: "Maldives",
    short_name: "MDV",
    status: "Country",
    dial_code: "+960",
    max_nsn_length: 7,
    flags_icon: "flags/mv.svg",
    national_language: "Dhivehi",
  },
  {
    id: 132,
    name: "Mali",
    short_name: "MLI",
    status: "Country",
    dial_code: "+223",
    max_nsn_length: 8,
    flags_icon: "flags/ml.svg",
    national_language: "French",
  },
  {
    id: 133,
    name: "Malta",
    short_name: "MLT",
    status: "Country",
    dial_code: "+356",
    max_nsn_length: 8,
    flags_icon: "flags/mt.svg",
    national_language: "Maltese",
  },
  {
    id: 134,
    name: "Marshall Islands",
    short_name: "MHL",
    status: "Country",
    dial_code: "+692",
    max_nsn_length: 7,
    flags_icon: "flags/mh.svg",
    national_language: "Marshallese",
  },
  {
    id: 135,
    name: "Martinique",
    short_name: "MQ",
    status: "Territory (France)",
    dial_code: "+596",
    max_nsn_length: 9,
    flags_icon: "flags/mq.svg",
    national_language: "French",
  },
  {
    id: 136,
    name: "Mauritania",
    short_name: "MRT",
    status: "Country",
    dial_code: "+222",
    max_nsn_length: 8,
    flags_icon: "flags/mr.svg",
    national_language: "Arabic",
  },
  {
    id: 137,
    name: "Mauritius",
    short_name: "MUS",
    status: "Country",
    dial_code: "+230",
    max_nsn_length: 8,
    flags_icon: "flags/mu.svg",
    national_language: "English",
  },
  {
    id: 138,
    name: "Mayotte",
    short_name: "YT",
    status: "Territory (France)",
    dial_code: "+262",
    max_nsn_length: 9,
    flags_icon: "flags/yt.svg",
    national_language: "French",
  },
  {
    id: 139,
    name: "Mexico",
    short_name: "MEX",
    status: "Country",
    dial_code: "+52",
    max_nsn_length: 10,
    flags_icon: "flags/mx.svg",
    national_language: "Spanish",
  },
  {
    id: 140,
    name: "Micronesia, Federated States of",
    short_name: "FSM",
    status: "Country",
    dial_code: "+691",
    max_nsn_length: 7,
    flags_icon: "flags/fm.svg",
    national_language: "English",
  },
  {
    id: 141,
    name: "Moldova",
    short_name: "MDA",
    status: "Country",
    dial_code: "+373",
    max_nsn_length: 8,
    flags_icon: "flags/md.svg",
    national_language: "Romanian",
  },
  {
    id: 142,
    name: "Monaco",
    short_name: "MCO",
    status: "Country",
    dial_code: "+377",
    max_nsn_length: 8,
    flags_icon: "flags/mc.svg",
    national_language: "French",
  },
  {
    id: 143,
    name: "Mongolia",
    short_name: "MNG",
    status: "Country",
    dial_code: "+976",
    max_nsn_length: 8,
    flags_icon: "flags/mn.svg",
    national_language: "Mongolian",
  },
  {
    id: 144,
    name: "Montenegro",
    short_name: "MNE",
    status: "Country",
    dial_code: "+382",
    max_nsn_length: 8,
    flags_icon: "flags/me.svg",
    national_language: "Montenegrin",
  },
  {
    id: 145,
    name: "Montserrat",
    short_name: "MS",
    status: "Territory (UK)",
    dial_code: "+1-664",
    max_nsn_length: 10,
    flags_icon: "flags/ms.svg",
    national_language: "English",
  },
  {
    id: 146,
    name: "Morocco",
    short_name: "MAR",
    status: "Country",
    dial_code: "+212",
    max_nsn_length: 9,
    flags_icon: "flags/ma.svg",
    national_language: "Arabic",
  },
  {
    id: 147,
    name: "Mozambique",
    short_name: "MOZ",
    status: "Country",
    dial_code: "+258",
    max_nsn_length: 9,
    flags_icon: "flags/mz.svg",
    national_language: "Portuguese",
  },
  {
    id: 148,
    name: "Myanmar (Burma)",
    short_name: "MMR",
    status: "Country",
    dial_code: "+95",
    max_nsn_length: 9,
    flags_icon: "flags/mm.svg",
    national_language: "Burmese",
  },
  {
    id: 149,
    name: "Namibia",
    short_name: "NAM",
    status: "Country",
    dial_code: "+264",
    max_nsn_length: 9,
    flags_icon: "flags/na.svg",
    national_language: "English",
  },
  {
    id: 150,
    name: "Nauru",
    short_name: "NRU",
    status: "Country",
    dial_code: "+674",
    max_nsn_length: 7,
    flags_icon: "flags/nr.svg",
    national_language: "Nauruan",
  },
  {
    id: 151,
    name: "Nepal",
    short_name: "NPL",
    status: "Country",
    dial_code: "+977",
    max_nsn_length: 10,
    flags_icon: "flags/np.svg",
    national_language: "Nepali",
  },
  {
    id: 152,
    name: "Netherlands",
    short_name: "NLD",
    status: "Country",
    dial_code: "+31",
    max_nsn_length: 9,
    flags_icon: "flags/nl.svg",
    national_language: "Dutch",
  },
  {
    id: 153,
    name: "New Caledonia",
    short_name: "NC",
    status: "Territory (France)",
    dial_code: "+687",
    max_nsn_length: 6,
    flags_icon: "flags/nc.svg",
    national_language: "French",
  },
  {
    id: 154,
    name: "New Zealand",
    short_name: "NZL",
    status: "Country",
    dial_code: "+64",
    max_nsn_length: 10,
    flags_icon: "flags/nz.svg",
    national_language: "English",
  },
  {
    id: 155,
    name: "Nicaragua",
    short_name: "NIC",
    status: "Country",
    dial_code: "+505",
    max_nsn_length: 8,
    flags_icon: "flags/ni.svg",
    national_language: "Spanish",
  },
  {
    id: 156,
    name: "Niger",
    short_name: "NER",
    status: "Country",
    dial_code: "+227",
    max_nsn_length: 8,
    flags_icon: "flags/ne.svg",
    national_language: "French",
  },
  {
    id: 157,
    name: "Nigeria",
    short_name: "NGA",
    status: "Country",
    dial_code: "+234",
    max_nsn_length: 10,
    flags_icon: "flags/ng.svg",
    national_language: "English",
  },
  {
    id: 158,
    name: "Niue",
    short_name: "NU",
    status: "Territory (New Zealand)",
    dial_code: "+683",
    max_nsn_length: 4,
    flags_icon: "flags/nu.svg",
    national_language: "Niuean",
  },
  {
    id: 159,
    name: "Norfolk Island",
    short_name: "NF",
    status: "Territory (Australia)",
    dial_code: "+672",
    max_nsn_length: 6,
    flags_icon: "flags/nf.svg",
    national_language: "English",
  },
  {
    id: 160,
    name: "North Korea",
    short_name: "PRK",
    status: "Country",
    dial_code: "+850",
    max_nsn_length: 11,
    flags_icon: "flags/kp.svg",
    national_language: "Korean",
  },
  {
    id: 161,
    name: "North Macedonia",
    short_name: "MKD",
    status: "Country",
    dial_code: "+389",
    max_nsn_length: 8,
    flags_icon: "flags/mk.svg",
    national_language: "Macedonian",
  },
  {
    id: 162,
    name: "Northern Mariana Islands",
    short_name: "MP",
    status: "Territory (USA)",
    dial_code: "+1-670",
    max_nsn_length: 10,
    flags_icon: "flags/mp.svg",
    national_language: "English",
  },
  {
    id: 163,
    name: "Norway",
    short_name: "NOR",
    status: "Country",
    dial_code: "+47",
    max_nsn_length: 8,
    flags_icon: "flags/no.svg",
    national_language: "Norwegian",
  },
  {
    id: 164,
    name: "Oman",
    short_name: "OMN",
    status: "Country",
    dial_code: "+968",
    max_nsn_length: 8,
    flags_icon: "flags/om.svg",
    national_language: "Arabic",
  },
  {
    id: 165,
    name: "Pakistan",
    short_name: "PAK",
    status: "Country",
    dial_code: "+92",
    max_nsn_length: 10,
    flags_icon: "flags/pk.svg",
    national_language: "Urdu",
  },
  {
    id: 166,
    name: "Palau",
    short_name: "PLW",
    status: "Country",
    dial_code: "+680",
    max_nsn_length: 7,
    flags_icon: "flags/pw.svg",
    national_language: "Palauan",
  },
  {
    id: 167,
    name: "Palestine, State of",
    short_name: "PSE",
    status: "Observer State",
    dial_code: "+970",
    max_nsn_length: 9,
    flags_icon: "flags/ps.svg",
    national_language: "Arabic",
  },
  {
    id: 168,
    name: "Panama",
    short_name: "PAN",
    status: "Country",
    dial_code: "+507",
    max_nsn_length: 8,
    flags_icon: "flags/pa.svg",
    national_language: "Spanish",
  },
  {
    id: 169,
    name: "Papua New Guinea",
    short_name: "PNG",
    status: "Country",
    dial_code: "+675",
    max_nsn_length: 8,
    flags_icon: "flags/pg.svg",
    national_language: "Tok Pisin",
  },
  {
    id: 170,
    name: "Paraguay",
    short_name: "PRY",
    status: "Country",
    dial_code: "+595",
    max_nsn_length: 9,
    flags_icon: "flags/py.svg",
    national_language: "Spanish",
  },
  {
    id: 171,
    name: "Peru",
    short_name: "PER",
    status: "Country",
    dial_code: "+51",
    max_nsn_length: 9,
    flags_icon: "flags/pe.svg",
    national_language: "Spanish",
  },
  {
    id: 172,
    name: "Philippines",
    short_name: "PHL",
    status: "Country",
    dial_code: "+63",
    max_nsn_length: 10,
    flags_icon: "flags/ph.svg",
    national_language: "Filipino",
  },
  {
    id: 173,
    name: "Pitcairn, Henderson, Ducie and Oeno Islands",
    short_name: "PN",
    status: "Territory (UK)",
    dial_code: "+64",
    max_nsn_length: 10,
    flags_icon: "flags/pn.svg",
    national_language: "English",
  },
  {
    id: 174,
    name: "Poland",
    short_name: "POL",
    status: "Country",
    dial_code: "+48",
    max_nsn_length: 9,
    flags_icon: "flags/pl.svg",
    national_language: "Polish",
  },
  {
    id: 175,
    name: "Portugal",
    short_name: "PRT",
    status: "Country",
    dial_code: "+351",
    max_nsn_length: 9,
    flags_icon: "flags/pt.svg",
    national_language: "Portuguese",
  },
  {
    id: 176,
    name: "Puerto Rico",
    short_name: "PR",
    status: "Territory (USA)",
    dial_code: "+1-787",
    max_nsn_length: 10,
    flags_icon: "flags/pr.svg",
    national_language: "Spanish",
  },
  {
    id: 177,
    name: "Qatar",
    short_name: "QAT",
    status: "Country",
    dial_code: "+974",
    max_nsn_length: 8,
    flags_icon: "flags/qa.svg",
    national_language: "Arabic",
  },
  {
    id: 178,
    name: "Réunion",
    short_name: "RE",
    status: "Territory (France)",
    dial_code: "+262",
    max_nsn_length: 9,
    flags_icon: "flags/re.svg",
    national_language: "French",
  },
  {
    id: 179,
    name: "Romania",
    short_name: "ROU",
    status: "Country",
    dial_code: "+40",
    max_nsn_length: 10,
    flags_icon: "flags/ro.svg",
    national_language: "Romanian",
  },
  {
    id: 180,
    name: "Russia",
    short_name: "RUS",
    status: "Country",
    dial_code: "+7",
    max_nsn_length: 10,
    flags_icon: "flags/ru.svg",
    national_language: "Russian",
  },
  {
    id: 181,
    name: "Rwanda",
    short_name: "RWA",
    status: "Country",
    dial_code: "+250",
    max_nsn_length: 8,
    flags_icon: "flags/rw.svg",
    national_language: "Kinyarwanda",
  },
  {
    id: 182,
    name: "Saint Barthélemy",
    short_name: "BL",
    status: "Territory (France)",
    dial_code: "+590",
    max_nsn_length: 9,
    flags_icon: "flags/bl.svg",
    national_language: "French",
  },
  {
    id: 183,
    name: "Saint Helena, Ascension and Tristan da Cunha",
    short_name: "SH",
    status: "Territory (UK)",
    dial_code: "+290",
    max_nsn_length: 4,
    flags_icon: "flags/sh.svg",
    national_language: "English",
  },
  {
    id: 184,
    name: "Saint Kitts and Nevis",
    short_name: "KNA",
    status: "Country",
    dial_code: "+1-869",
    max_nsn_length: 10,
    flags_icon: "flags/kn.svg",
    national_language: "English",
  },
  {
    id: 185,
    name: "Saint Lucia",
    short_name: "LCA",
    status: "Country",
    dial_code: "+1-758",
    max_nsn_length: 10,
    flags_icon: "flags/lc.svg",
    national_language: "English",
  },
  {
    id: 186,
    name: "Saint Martin",
    short_name: "MF",
    status: "Territory (France)",
    dial_code: "+590",
    max_nsn_length: 9,
    flags_icon: "flags/mf.svg",
    national_language: "French",
  },
  {
    id: 187,
    name: "Saint Pierre and Miquelon",
    short_name: "PM",
    status: "Territory (France)",
    dial_code: "+508",
    max_nsn_length: 6,
    flags_icon: "flags/pm.svg",
    national_language: "French",
  },
  {
    id: 188,
    name: "Saint Vincent and the Grenadines",
    short_name: "VCT",
    status: "Country",
    dial_code: "+1-784",
    max_nsn_length: 10,
    flags_icon: "flags/vc.svg",
    national_language: "English",
  },
  {
    id: 189,
    name: "Samoa",
    short_name: "WSM",
    status: "Country",
    dial_code: "+685",
    max_nsn_length: 7,
    flags_icon: "flags/ws.svg",
    national_language: "Samoan",
  },
  {
    id: 190,
    name: "San Marino",
    short_name: "SMR",
    status: "Country",
    dial_code: "+378",
    max_nsn_length: 10,
    flags_icon: "flags/sm.svg",
    national_language: "Italian",
  },
  {
    id: 191,
    name: "São Tomé and Príncipe",
    short_name: "STP",
    status: "Country",
    dial_code: "+239",
    max_nsn_length: 7,
    flags_icon: "flags/st.svg",
    national_language: "Portuguese",
  },
  {
    id: 192,
    name: "Saudi Arabia",
    short_name: "SAU",
    status: "Country",
    dial_code: "+966",
    max_nsn_length: 9,
    flags_icon: "flags/sa.svg",
    national_language: "Arabic",
  },
  {
    id: 193,
    name: "Senegal",
    short_name: "SEN",
    status: "Country",
    dial_code: "+221",
    max_nsn_length: 9,
    flags_icon: "flags/sn.svg",
    national_language: "French",
  },
  {
    id: 194,
    name: "Serbia",
    short_name: "SRB",
    status: "Country",
    dial_code: "+381",
    max_nsn_length: 9,
    flags_icon: "flags/rs.svg",
    national_language: "Serbian",
  },
  {
    id: 195,
    name: "Seychelles",
    short_name: "SYC",
    status: "Country",
    dial_code: "+248",
    max_nsn_length: 7,
    flags_icon: "flags/sc.svg",
    national_language: "Seychellois Creole",
  },
  {
    id: 196,
    name: "Sierra Leone",
    short_name: "SLE",
    status: "Country",
    dial_code: "+232",
    max_nsn_length: 8,
    flags_icon: "flags/sl.svg",
    national_language: "English",
  },
  {
    id: 197,
    name: "Singapore",
    short_name: "SGP",
    status: "Country",
    dial_code: "+65",
    max_nsn_length: 8,
    flags_icon: "flags/sg.svg",
    national_language: "Malay",
  },
  {
    id: 198,
    name: "Sint Maarten",
    short_name: "SX",
    status: "Territory (Netherlands)",
    dial_code: "+1-721",
    max_nsn_length: 10,
    flags_icon: "flags/sx.svg",
    national_language: "English",
  },
  {
    id: 199,
    name: "Slovakia",
    short_name: "SVK",
    status: "Country",
    dial_code: "+421",
    max_nsn_length: 9,
    flags_icon: "flags/sk.svg",
    national_language: "Slovak",
  },
  {
    id: 200,
    name: "Slovenia",
    short_name: "SVN",
    status: "Country",
    dial_code: "+386",
    max_nsn_length: 8,
    flags_icon: "flags/si.svg",
    national_language: "Slovenian",
  },
  {
    id: 201,
    name: "Solomon Islands",
    short_name: "SLB",
    status: "Country",
    dial_code: "+677",
    max_nsn_length: 7,
    flags_icon: "flags/sb.svg",
    national_language: "English",
  },
  {
    id: 202,
    name: "Somalia",
    short_name: "SOM",
    status: "Country",
    dial_code: "+252",
    max_nsn_length: 8,
    flags_icon: "flags/so.svg",
    national_language: "Somali",
  },
  {
    id: 203,
    name: "South Africa",
    short_name: "ZAF",
    status: "Country",
    dial_code: "+27",
    max_nsn_length: 9,
    flags_icon: "flags/za.svg",
    national_language: "Zulu",
  },
  {
    id: 204,
    name: "South Georgia and the South Sandwich Islands",
    short_name: "GS",
    status: "Territory (UK)",
    dial_code: "+500",
    max_nsn_length: 5,
    flags_icon: "flags/gs.svg",
    national_language: "English",
  },
  {
    id: 205,
    name: "South Korea",
    short_name: "KOR",
    status: "Country",
    dial_code: "+82",
    max_nsn_length: 11,
    flags_icon: "flags/kr.svg",
    national_language: "Korean",
  },
  {
    id: 206,
    name: "South Sudan",
    short_name: "SSD",
    status: "Country",
    dial_code: "+211",
    max_nsn_length: 9,
    flags_icon: "flags/ss.svg",
    national_language: "English",
  },
  {
    id: 207,
    name: "Spain",
    short_name: "ESP",
    status: "Country",
    dial_code: "+34",
    max_nsn_length: 9,
    flags_icon: "flags/es.svg",
    national_language: "Spanish",
  },
  {
    id: 208,
    name: "Sri Lanka",
    short_name: "LKA",
    status: "Country",
    dial_code: "+94",
    max_nsn_length: 9,
    flags_icon: "flags/lk.svg",
    national_language: "Sinhala",
  },
  {
    id: 209,
    name: "Sudan",
    short_name: "SDN",
    status: "Country",
    dial_code: "+249",
    max_nsn_length: 9,
    flags_icon: "flags/sd.svg",
    national_language: "Arabic",
  },
  {
    id: 210,
    name: "Suriname",
    short_name: "SUR",
    status: "Country",
    dial_code: "+597",
    max_nsn_length: 7,
    flags_icon: "flags/sr.svg",
    national_language: "Dutch",
  },
  {
    id: 211,
    name: "Svalbard and Jan Mayen",
    short_name: "SJ",
    status: "Territory (Norway)",
    dial_code: "+47",
    max_nsn_length: 8,
    flags_icon: "flags/sj.svg",
    national_language: "Norwegian",
  },
  {
    id: 212,
    name: "Sweden",
    short_name: "SWE",
    status: "Country",
    dial_code: "+46",
    max_nsn_length: 13,
    flags_icon: "flags/se.svg",
    national_language: "Swedish",
  },
  {
    id: 213,
    name: "Switzerland",
    short_name: "CHE",
    status: "Country",
    dial_code: "+41",
    max_nsn_length: 9,
    flags_icon: "flags/ch.svg",
    national_language: "German",
  },
  {
    id: 214,
    name: "Syria",
    short_name: "SYR",
    status: "Country",
    dial_code: "+963",
    max_nsn_length: 10,
    flags_icon: "flags/sy.svg",
    national_language: "Arabic",
  },
  {
    id: 215,
    name: "Taiwan",
    short_name: "TWN",
    status: "Country (Partial Recognition)",
    dial_code: "+886",
    max_nsn_length: 10,
    flags_icon: "flags/tw.svg",
    national_language: "Mandarin Chinese",
  },
  {
    id: 216,
    name: "Tajikistan",
    short_name: "TJK",
    status: "Country",
    dial_code: "+992",
    max_nsn_length: 9,
    flags_icon: "flags/tj.svg",
    national_language: "Tajik",
  },
  {
    id: 217,
    name: "Tanzania",
    short_name: "TZA",
    status: "Country",
    dial_code: "+255",
    max_nsn_length: 9,
    flags_icon: "flags/tz.svg",
    national_language: "Swahili",
  },
  {
    id: 218,
    name: "Thailand",
    short_name: "THA",
    status: "Country",
    dial_code: "+66",
    max_nsn_length: 10,
    flags_icon: "flags/th.svg",
    national_language: "Thai",
  },
  {
    id: 219,
    name: "Timor-Leste (East Timor)",
    short_name: "TLS",
    status: "Country",
    dial_code: "+670",
    max_nsn_length: 8,
    flags_icon: "flags/tl.svg",
    national_language: "Tetum",
  },
  {
    id: 220,
    name: "Togo",
    short_name: "TGO",
    status: "Country",
    dial_code: "+228",
    max_nsn_length: 8,
    flags_icon: "flags/tg.svg",
    national_language: "French",
  },
  {
    id: 221,
    name: "Tokelau",
    short_name: "TK",
    status: "Territory (New Zealand)",
    dial_code: "+690",
    max_nsn_length: 4,
    flags_icon: "flags/tk.svg",
    national_language: "Tokelauan",
  },
  {
    id: 222,
    name: "Tonga",
    short_name: "TON",
    status: "Country",
    dial_code: "+676",
    max_nsn_length: 7,
    flags_icon: "flags/to.svg",
    national_language: "Tongan",
  },
  {
    id: 223,
    name: "Trinidad and Tobago",
    short_name: "TTO",
    status: "Country",
    dial_code: "+1-868",
    max_nsn_length: 10,
    flags_icon: "flags/tt.svg",
    national_language: "English",
  },
  {
    id: 224,
    name: "Tunisia",
    short_name: "TUN",
    status: "Country",
    dial_code: "+216",
    max_nsn_length: 8,
    flags_icon: "flags/tn.svg",
    national_language: "Arabic",
  },
  {
    id: 225,
    name: "Turkey",
    short_name: "TUR",
    status: "Country",
    dial_code: "+90",
    max_nsn_length: 10,
    flags_icon: "flags/tr.svg",
    national_language: "Turkish",
  },
  {
    id: 226,
    name: "Turkmenistan",
    short_name: "TKM",
    status: "Country",
    dial_code: "+993",
    max_nsn_length: 8,
    flags_icon: "flags/tm.svg",
    national_language: "Turkmen",
  },
  {
    id: 227,
    name: "Turks and Caicos Islands",
    short_name: "TC",
    status: "Territory (UK)",
    dial_code: "+1-649",
    max_nsn_length: 10,
    flags_icon: "flags/tc.svg",
    national_language: "English",
  },
  {
    id: 228,
    name: "Tuvalu",
    short_name: "TUV",
    status: "Country",
    dial_code: "+688",
    max_nsn_length: 5,
    flags_icon: "flags/tv.svg",
    national_language: "Tuvaluan",
  },
  {
    id: 229,
    name: "Uganda",
    short_name: "UGA",
    status: "Country",
    dial_code: "+256",
    max_nsn_length: 9,
    flags_icon: "flags/ug.svg",
    national_language: "English",
  },
  {
    id: 230,
    name: "Ukraine",
    short_name: "UKR",
    status: "Country",
    dial_code: "+380",
    max_nsn_length: 9,
    flags_icon: "flags/ua.svg",
    national_language: "Ukrainian",
  },
  {
    id: 231,
    name: "United Arab Emirates (UAE)",
    short_name: "UAE",
    status: "Country",
    dial_code: "+971",
    max_nsn_length: 9,
    flags_icon: "flags/ae.svg",
    national_language: "Arabic",
  },
  {
    id: 232,
    name: "United Kingdom (UK)",
    short_name: "UK",
    status: "Country",
    dial_code: "+44",
    max_nsn_length: 10,
    flags_icon: "flags/gb.svg",
    national_language: "English",
  },
  {
    id: 233,
    name: "United States (USA)",
    short_name: "USA",
    status: "Country",
    dial_code: "+1",
    max_nsn_length: 10,
    flags_icon: "flags/us.svg",
    national_language: "English",
  },
  {
    id: 234,
    name: "Uruguay",
    short_name: "URY",
    status: "Country",
    dial_code: "+598",
    max_nsn_length: 8,
    flags_icon: "flags/uy.svg",
    national_language: "Spanish",
  },
  {
    id: 235,
    name: "U.S. Virgin Islands",
    short_name: "VI",
    status: "Territory (USA)",
    dial_code: "+1-340",
    max_nsn_length: 10,
    flags_icon: "flags/vi.svg",
    national_language: "English",
  },
  {
    id: 236,
    name: "Uzbekistan",
    short_name: "UZB",
    status: "Country",
    dial_code: "+998",
    max_nsn_length: 9,
    flags_icon: "flags/uz.svg",
    national_language: "Uzbek",
  },
  {
    id: 237,
    name: "Vanuatu",
    short_name: "VUT",
    status: "Country",
    dial_code: "+678",
    max_nsn_length: 7,
    flags_icon: "flags/vu.svg",
    national_language: "Bislama",
  },
  {
    id: 238,
    name: "Venezuela",
    short_name: "VEN",
    status: "Country",
    dial_code: "+58",
    max_nsn_length: 10,
    flags_icon: "flags/ve.svg",
    national_language: "Spanish",
  },
  {
    id: 239,
    name: "Vietnam",
    short_name: "VNM",
    status: "Country",
    dial_code: "+84",
    max_nsn_length: 11,
    flags_icon: "flags/vn.svg",
    national_language: "Vietnamese",
  },
  {
    id: 240,
    name: "Wallis and Futuna",
    short_name: "WF",
    status: "Territory (France)",
    dial_code: "+681",
    max_nsn_length: 6,
    flags_icon: "flags/wf.svg",
    national_language: "French",
  },
  {
    id: 241,
    name: "Western Sahara",
    short_name: "ESH",
    status: "Disputed Territory",
    dial_code: "+212",
    max_nsn_length: 9,
    flags_icon: "flags/eh.svg",
    national_language: "Arabic",
  },
  {
    id: 242,
    name: "Yemen",
    short_name: "YEM",
    status: "Country",
    dial_code: "+967",
    max_nsn_length: 9,
    flags_icon: "flags/ye.svg",
    national_language: "Arabic",
  },
  {
    id: 243,
    name: "Zambia",
    short_name: "ZMB",
    status: "Country",
    dial_code: "+260",
    max_nsn_length: 9,
    flags_icon: "flags/zm.svg",
    national_language: "English",
  },
  {
    id: 244,
    name: "Zimbabwe",
    short_name: "ZWE",
    status: "Country",
    dial_code: "+263",
    max_nsn_length: 9,
    flags_icon: "flags/zw.svg",
    national_language: "English",
  },
];

module.exports = updatedData;